application: sampyxis-tasks
version: 1
runtime: python
api_version: 1

inbound_services:
   - mail
    
handlers:
- url: /_ah/mail/.+
  script: handle_email.py

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: .*
  script: tasks.py
  


